import fs from "fs";
import path from "path";

function extractSection(md: string, header: string): string | null {
  const idx = md.indexOf(header);
  if (idx === -1) return null;
  return md.slice(idx);
}

/**
 * Loads a Postgres schema reference (generated by `scripts/dump-schema.ts`) and
 * trims it to keep LLM context high-signal (tables/columns + foreign keys).
 */
export function loadDatabaseSchemaForPrompt(): string {
  const schemaPath = path.join(process.cwd(), "DATABASE_SCHEMA.md");
  try {
    const raw = fs.readFileSync(schemaPath, "utf8");

    // Keep: header + tables overview + table columns
    const beforeIndexes = raw.split("\n## Indexes\n")[0]?.trim() ?? raw.trim();

    // Also keep Foreign Keys (but skip Indexes + Sample Data for token efficiency)
    const fks = extractSection(raw, "## Foreign Keys")?.split("\n## Sample Data\n")[0]?.trim();

    return [beforeIndexes, fks].filter(Boolean).join("\n\n").trim();
  } catch {
    // Fallback keeps the assistant functional even if the schema file isn't present.
    return [
      "Database Schema Reference: (missing `DATABASE_SCHEMA.md`)",
      "Known core tables: spend_entries, buyers, suppliers, entities, nhs_organisations, councils, companies, contracts.",
      "Tip: Run `pnpm tsx scripts/dump-schema.ts` to generate `DATABASE_SCHEMA.md`.",
    ].join("\n");
  }
}


